# Generated by Django 4.0.3 on 2022-03-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('director', models.CharField(max_length=30)),
                ('length_minutes', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('director', models.CharField(max_length=30)),
                ('length_minutes', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('seasons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('artist', models.CharField(max_length=30)),
                ('length_minutes', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
